# Generated by Django 4.2.20 on 2025-05-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_profesionalsalud_rename_eda_paciente_edad_tecnico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.DateField()),
                ('descripcion', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medicos', to='usuarios.paciente')),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medicos', to='usuarios.profesionalsalud')),
            ],
        ),
        migrations.CreateModel(
            name='Preescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('evento_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='eventosMedicos.eventomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('examen_fisico', models.TextField()),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField()),
                ('evento_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='eventosMedicos.eventomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cirugia', models.CharField(max_length=100)),
                ('fecha_cirugia', models.DateField()),
                ('riesgos', models.TextField()),
                ('evento_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='eventosMedicos.eventomedico')),
            ],
        ),
    ]
