# Generated by Django 4.2.21 on 2025-05-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventosMedicos', '0003_cita_alter_cirugia_id_alter_consulta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='lugar',
            field=models.CharField(default='Consultorio General', max_length=200),
        ),
        migrations.AddField(
            model_name='cita',
            name='numero_reserva',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
    ]
