# Generated by Django 4.2.20 on 2025-05-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_task_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_medico', models.CharField(max_length=20, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_salud', to='usuarios.usuario')),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='eda',
            new_name='edad',
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_examen', models.CharField(max_length=100)),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='usuarios.profesionalsalud')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_especialidad', models.CharField(max_length=100)),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermeros', to='usuarios.profesionalsalud')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('consultorio', models.CharField(max_length=100)),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='usuarios.profesionalsalud')),
            ],
        ),
    ]
