# Generated by Django 4.2.21 on 2025-05-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20250502_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
